blog/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^blog$', views.post_list, name='post_list'),
    url(r'^blog/$', views.post_list, name='post_list'),
    url(r'^post/(?P<pk>[0-9]+)/$', views.post_detail, name='post_detail'),
    url(r'^event/(?P<pk>[0-9]+)/$', views.event_detail, name='event_detail'),
     url(r'^events/$', views.event_calendar, name='event_calendar'),
    url(r'^comment/(?P<pk>[0-9]+)/approve/$', views.comment_approve, name='comment_approve'),
    url(r'^comment/(?P<pk>[0-9]+)/remove/$', views.comment_remove, name='comment_remove'),
]

centurion/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^', include('blog.urls')),
    url(r'^',include('content.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

blog/models.py
from django.db import models

# Create your models here.
from django.db import models
from django.utils import timezone
from tinymce import models as tinymce_models

class Event(models.Model):
    title = models.CharField(max_length=200)
    text = tinymce_models.HTMLField(blank=True, null=True, help_text="Enter a short description.")
    img = models.ImageField(null=True, blank=True)
    poster = models.FileField(null=True, blank=True)
    start_time = models.DateTimeField(default=timezone.now, blank=True, null=True)
    end_time = models.DateTimeField(default=timezone.now, blank=True, null=True)
    link = models.URLField(
        max_length=200, help_text="Please enter a link to register for the event", blank=True, null=True)
    button_text = models.CharField(
        blank=True, null=True, max_length=100, default="Register now")

    def __str__(self):
        return self.title



class Post(models.Model):
    author= models.ForeignKey('auth.User')
    title = models.CharField(max_length=200)
    text = tinymce_models.HTMLField(blank=True, null=True, help_text="Enter a short description.")
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)
    img = models.ImageField(null=True, blank=True)
    
    def publish(self):
        self.publish_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

    def approved_comments(self):
        return self.comments.filter(approved_comment=True)

class Comment(models.Model):
    post = models.ForeignKey('blog.Post', related_name='comments')
    author = models.CharField(max_length=200)
    text = tinymce_models.HTMLField()
    created_date = models.DateTimeField(default=timezone.now)
    approved_comment = models.BooleanField(default=False)

    def approve(self):
        self.approved_comment = True
        self.save()

    def __str__(self):
        return self.text

content/models.py
from django.db import models
from django.utils import timezone
from tinymce import models as tinymce_models
from django.utils.safestring import mark_safe
# Create your models here.


class Header(models.Model):
    background_image = models.ImageField(blank=True, null=True)
    title = models.CharField(blank=True, null=True, max_length=100)
    subtitle = models.CharField(blank=True, null=True, max_length=100)
    link = models.URLField(
        max_length=200, help_text="Please enter a link for learn more button", blank=True, null=True)
    button_text = models.CharField(
        blank=True, null=True, max_length=100, default="Learn More")
    link2 = models.URLField(max_length=200, blank=True, null=True,
                            help_text="Please enter a link for learn more button", )
    button_text2 = models.CharField(
        blank=True, null=True, max_length=100, default="Learn More")

    def __str__(self):
        return self.title

class SubHeader(models.Model):
    title = models.CharField(blank=True, null=True, max_length=100)
    subtitle = models.TextField(blank=True, null=True)
    link = models.URLField(
        max_length=200, help_text="Please enter a link for learn more button", blank=True, null=True)
    button_text = models.CharField(
        blank=True, null=True, max_length=100, default="Learn More")

    def __str__(self):
        return self.title

class HomeIcon(models.Model):
    title = models.CharField(blank=True, null=True, max_length=100)
    text = models.CharField(blank=True, null=True, max_length=100)
    icon = models.CharField(blank=True, null=True, max_length=100, default="fa-heart", help_text=mark_safe(
        "Please write in which icon you'd like, ie fa-phone. Check <a href='http://fontawesome.io/icons/'>here</a> for icons."))

    def __str__(self):
        return self.title


class CarouselImage(models.Model):
    image = models.ImageField(blank=True, null=True,
                                       help_text="this will be a sliding images on the homepage")
    title = models.CharField(blank=True, null=True, max_length=100)
    carousel_text = models.CharField(blank=True, null=True, max_length=100)

    def __str__(self):
        return self.title

# class SmallImage(models.Model):
#     image = models.ImageField(blank=True, null=True,
#                                        help_text="small rounded image on homepage")
#     title = models.CharField(blank=True, null=True, max_length=100)
#     subtitle = models.CharField(blank=True, null=True, max_length=100)
#     text = models.CharField(blank=True, null=True, max_length=300)

#     def __str__(self):
#         return self.title

blog/forms.py
from django import forms

from .models import Post, Comment

class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('title', 'text',)

class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('author', 'text',)

    class Media:
        js = ('/media/tinymce/jscripts/tiny_mce/tiny_mce.js',
                '/sitemedia/js/tinymce_setup.js',)

blog/views.py
from django.utils import timezone
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post, Comment, Event
from .forms import PostForm, CommentForm
from django.contrib.auth.decorators import login_required
# Create your views here.


def post_list(request):
    posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')
    return render(request,'blog/post_list.html',{'posts': posts})

def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.save()
            return redirect('blog.views.post_detail', pk=post.pk)
    else:
        form = CommentForm()
    return render(request, 'blog/post_detail.html', {'form': form, 'post': post})


def event_list(request):
    events = Event.objects.filter(start_time__gte=timezone.now()).order_by('start_time')
    return render(request,'blog/event_list.html',{'events': events})

def event_calendar(request):
    events = Event.objects.filter(start_time__gte=timezone.now()).order_by('start_time')
    return render(request,'blog/calendar.html',{'events': events})

def event_detail(request, pk):
    event = get_object_or_404(Event, pk=pk)
    return render(request, 'blog/event_detail.html', {'event': event})

@login_required
def post_new(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('blog.views.post_detail', pk=post.pk)
    else:
        form = PostForm()
    return render(request, 'blog/post_edit.html', {'form': form})

@login_required
def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('blog.views.post_detail', pk=post.pk)
    else:
        form = PostForm(instance=post)
    return render(request, 'blog/post_edit.html', {'form': form})

@login_required
def post_publish(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.publish()
    return redirect('blog.views.post_detail', pk=pk)

@login_required
def publish(self):
    self.published_date = timezone.now()
    self.save()

@login_required
def post_remove(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.delete()
    return redirect('blog.views.post_list')


@login_required
def comment_approve(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    comment.approve()
    return redirect('blog.views.post_detail', pk=comment.post.pk)

@login_required
def comment_remove(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    post_pk = comment.post.pk
    comment.delete()
    return redirect('blog.views.post_detail', pk=post_pk)

blog/templates/blog/blog_base.html
{% extends "base.html" %}
{% load static %}
{% block page-content %}
{% block header %}
    <div class="wrapper">
        <div class="page-header page-header-xs" data-parallax="true" style="background-image: url({% static 'img/martial-arts.jpg' %});">
			<div class="filter"></div>
        </div>
        <div class="section profile-content">
                <div class="container">
                    <div class="owner">
                        <div class="avatar">
                                <img style="max-width: 100%; margin:10;" src="{% static 'images/CenturionShield.png' %}" alt="Centurion MSC Logo Sheild" class="img-no-padding img-responsive">
                            </div>
                    </div>
        {% endblock header %}
        {% block content %}
        {% endblock content %}
    </div>

  
{% endblock page-content %}

blog/templates/blog/calendar.html
{% extends "blog/blog_base.html" %}
{% load static %}
{% block header %}
<div class="wrapper">
    <div class="page-header page-header-xs" data-parallax="true" style="background-image: url({% static 'img/notebook.jpg' %});">
  <div class="filter"></div>
    </div>
    <div class="section profile-content">
            <div class="container">
                <div class="owner">
                    <div class="avatar">
                            <img style="max-width: 100%; margin:10;" src="{% static 'images/CenturionShield.png' %}" alt="Centurion MSC Logo Sheild" class="img-no-padding img-responsive">
                        </div>
                </div>
  {% endblock header %}
{% block content %}


    <div class="row">
        <div class="col-md-8 offset-md-2">
           {% if events %}
                    <div style="margin-top:3em;" id='calendar'></div>
            {% else %}
            <h2>No upcoming events, please check back soon!</h2>
          {% endif %}
        </div>
    </div>



{% endblock content %}

    {% block scripts %}
    
    <script src="{% static 'js/lib/moment.min.js'%}"></script>
    <script src="{% static 'js/lib/fullcalendar.min.js'%}"></script>
    
    <script>
            $(document).ready(function() {
        
              $('#calendar').fullCalendar({
                header: {
                  left: 'prev',
                  center: 'title',
                  right: 'today, next'
                },
                eventLimit: true, // allow "more" link when too many events
                eventRender: function(event, element, view) {
                    if(event.img){
                        if(event.allDay){
                            $(element).find('span:first').before('<img style="display:block;width:100%;min-height:132px;" src="'+event.img+'" />');
                        }else{
                            $(element).find('.fc-time').before('<img style="display:block;width:100%;min-height:132px;" src="'+event.img+'" />');
                        }
                    }
                },
                
                windowResize: function(view) {
                  setTimeout(function(){
                    $( ".fc-rigid" ).each( function(){
                      var h = $(this).children('.fc-content-skeleton').height() + 10;
                      $(this).css('height', h);
                    });
                  }, 300);
                },
                events: [
                
               
                {% for event in events %}
                
                  {
                    'title': "{{ event.title }}",
                    'start': "{% if event.start_time %}{{event.start_time|date:'c'}}{% endif %}",
                    'end': "{% if event.end_time %}{{event.end_time|date:'c'}}{% endif %}",
                    'url': "{% url "event_detail" pk=event.pk %}",
                    'image':  "{{ event.img }}",
                  },
                {% endfor %}
                ], 
                defaultDate: "{% for event in events %}{% if forloop.first %}{{event.start_time|date:'c'}}{% endif %}{% endfor %}",

              });
        
            });
        </script>
        
        
        {% endblock %}

blog/templates/blog/event_detail.html
{% extends "blog/blog_base.html" %}

{% block content %}

      <div class="row">
            <div class="col-md-8 offset-md-2">
                    <h2 class="card-title text-center">{{ event.title }} on {{ event.start_time|date:"D M d Y" }}</h2>
                    <div class="card card-profile card-plain">

                        <a href="#">
                                    {% if event.poster %}
                                <embed src="{{ event.poster.url }}" width="550" height="880" type='application/pdf'>
                                    {% elif event.image %}
                                    <img src="{{ event.image.url }}" alt="{{ event.title }} image" />
                                    {% endif %}
                            </a>
                        {{ event.text|safe }}
                            <a href="{{ event.link }}" class="btn btn-danger btn-round">{{ event.button_text }}</a>

                    </div>
                </div>
    </div>

{% endblock %}

blog/templates/blog/event_list.html
{% extends "blog/blog_base.html" %}

{% block content %}

    <div class="row">

      
      <div class="col-md-8 offset-md-2">

        {% for post  in  events %}
        <div  class="text-center">
          <h1><a href="{% url "event_detail" pk=post.pk %}">{{ post.title }}</a></h1>
          <p> Date: {{ post.date|date:"D M d Y" }}</p>
          <div class="border">

          {% if post.img %} <img class = "img-responsive img-rounded blogimage" src="{{ post.img.url }}">  {% endif %}
          <p class="blogcontent"> {{ post.text|striptags|truncatechars:200 }}</p>
        </div>
        {% endfor %}

      </div><!--close row-->
     </div>
    </div>

  {% endblock content %}

blog/templates/blog/post_detail.html
{% extends "blog/blog_base.html" %}

{% block content %}

      <div class="row">
        
          <div class="col-md-8 offset-md-2">
            <h1 class="text-center">{{ post.title }}</h1>
          {% if post.img %} <img class="img-responsive img-rounded text-center" style="margin:2em;width:100%" src="{{ post.img.url }}">  {% endif %}
          <p class="blogcontent">{{ post.text|safe }}</p>

          </div>
         
        <!--close the row-->
        </div>
      <div class="row">
        <div class="col-md-8 offset-md-2">
          {% for comment in post.comments.all %}
            {% if user.is_authenticated or comment.approved_comment %}
            <hr>
                <div class="date">
                    {{ comment.created_date }}
                    {% if not comment.approved_comment %}
                        <a class="btn btn-default removebtn" href="{% url "comment_remove" pk=comment.pk %}"><span class="glyphicon glyphicon-remove"></span></a>
                        <a class="btn btn-default okbtn" href="{% url "comment_approve" pk=comment.pk %}"><span class="glyphicon glyphicon-ok"></span></a>
                    {% endif %}
                </div>
                <strong>{{ comment.author }}</strong>
                <p class="comment">{{ comment.text|safe }}</p>
              {% endif %}
              {% if forloop.last %}

              <h3 class="title">New Comment</h3>
                <form method="POST" class="post-form" id="commentform" >{% csrf_token %}
                  <p><label for="id_author">Author:</label> <input id="id_author" maxlength="200" name="author" type="text"></p>
                  <p><label for="id_text">Text:</label> <textarea cols="40" id="id_text" name="text" rows="20"></textarea></p>
                  <button type="submit"
                    class="g-recaptcha save btn btn-default"
                    data-sitekey="6LcXVy0UAAAAACSKENWRUX-POo1H8EsdnDp-R5qx"
                    data-callback="submitcomment">
                    Submit
                  </button>
                  <script>
                      function submitcomment(){
                          document.getElementById('commentform').submit()
                      }
                  </script>
                
              </form>
    </div><!--close 8col-->

    </div><!--close row-->
   <!--  </div> --><!--close container-->
      {% endif %}
      {% empty %}

      <hr>
       <p>No comments here yet</p>
       <hr>
      <h3 class="title">New Comment</h3>
       <form method="POST" class="post-form" id="commentform">{% csrf_token %}
          <p><label for="id_author">Author:</label> <input id="id_author" maxlength="200" name="author" type="text"></p>
          <p><label for="id_text">Text:</label> <textarea cols="40" id="id_text" name="text" rows="10"></textarea></p>
          <button type="submit"
        class="g-recaptcha save btn btn-default"
        data-sitekey="6LcXVy0UAAAAACSKENWRUX-POo1H8EsdnDp-R5qx"
        data-callback="submitcomment">
        Submit
        </button>
        <script>
        function submitcomment(){
            document.getElementById('commentform').submit()
        }
    </script>
         
      </form>
    </div><!--close 8col-->

    </div><!--close row-->

      {% endfor %}
          </div>

        </div>
       

{% endblock %}

blog/templates/blog/post_list.html
{% extends "blog/blog_base.html" %}

{% block content %}

    <div class="row">

      
      <div class="col-md-8 offset-md-2">
        {% if posts %}
        {% for post  in  posts %}
        <div  class="text-center">
          <a href="{% url "post_detail" pk=post.pk %}"><h1>{{ post.title }}</h1></a>
          <p> Published: {{post.published_date}}</p>
          <div class="border">

          {% if post.img %} <img class = "img-responsive img-rounded blogimage" src="{{post.img.url}}">  {% endif %}
          <p class="blogcontent"> {{ post.text|striptags|truncatechars:200 }}</p>

          <a href="{% url 'post_detail' pk=post.pk %}" class="comment">Comments: {{ post.approved_comments.count }}</a>
        </div>
        {% endfor %}
        {% else %}
        <<h1>No posts yet, check back soon! </h1>
        {% endif %}
      </div>
     </div>
    </div>
  
  {% endblock content %}